---
# Path where the certificate authority (CA) certificates are stored.
ca_certificates_path: "/usr/local/share/ca-certificates"

# Files that will be copied to the CA certificates path.
ca_certificates:
  - "ca.lan.homelab.crt"

# SSH known hosts file.
ssh_known_hosts: "/etc/ssh/ssh_known_hosts"

# SSH CA public keys for host verification.
ssh_host_ca_keys:
  - "ca.lan.homelab.pub"

system_settings:
  # Sets the system's timezone.
  timezone: "America/Maceio"
  # NTP configuration for time synchronization.
  ntp:
    # Service to use: 'timesyncd' (recommended for clients) or 'chronyd' (for servers).
    service: "timesyncd"
    # Your Fortigate NTP server IP or hostname
    servers:
      - "ntp-pool.{{ domain }}"

  # Sets the boot menu timeout in seconds.
  grub_timeout: 2

# The name of the root user used in VM.
user_password_id: "local_admin"

# The hash type to be used when encrypting the user's password.
password_hash: "sha512"
