---
apt_packages:
  # System Essentials - Core system services and administrative tools.
  - {name: "sudo"} # Administrative privileges for system management.
  - {name: "qemu-guest-agent"} # Enhanced Proxmox VM integration and monitoring.
  - {name: "openssh-server"} # SSH remote access service.
  - {name: "cloud-init"} # VM initialization and provisioning service.
  # Python Environment - Development and automation tools.
  - {name: "python-is-python3"} # Python 3 as default Python interpreter.
  - {name: "pipx"} # Isolated Python package installation and management.
  - {name: "python3-psutil"} # System and process information library.
  - {name: "python3-passlib"} # Password hashing library with bcrypt support.
  - {name: "python3-jmespath"} # JSON query expressions for data processing.
  # Hardware & Drivers - Hardware support and driver management.
  - {name: "ubuntu-drivers-common"} # Latest hardware driver installation support.
