---
- name: "Including OS-specific or default variables for global packages"
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.codename }}.yml"
    - "packages.yml"

- name: "Installing global APT packages"
  ansible.builtin.include_role:
    name: "common"
    tasks_from: "debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: true
    packages: "{{ apt_packages }}"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: "flush_handlers"
